name: studiotwofour-4

volumes:
  data:
    driver: local

services:
      
  database:
    image: postgres
    restart: on-failure
    ports:
      - 9001:5432
    environment:
      POSTGRES_PASSWORD: 123454321
      POSTGRES_USER: studiotwofour_user
      POSTGRES_DB: studiotwofour
    volumes:
      - data:/var/lib/postgresql/data